//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace hyjiacan.py4n {
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class PinyinDbResource {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PinyinDbResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("hyjiacan.py4n.PinyinDbResource", typeof(PinyinDbResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 3007 (ling2)
        ///4E00 (yi1)
        ///4E01 (ding1,zheng1)
        ///4E02 (kao3)
        ///4E03 (qi1)
        ///4E04 (shang4,shang3)
        ///4E05 (xia4)
        ///4E06 (none0)
        ///4E07 (wan4,mo4)
        ///4E08 (zhang4)
        ///4E09 (san1)
        ///4E0A (shang4,shang3)
        ///4E0B (xia4)
        ///4E0C (ji1)
        ///4E0D (bu4,bu2,fou3)
        ///4E0E (yu3,yu4,yu2)
        ///4E0F (mian3)
        ///4E10 (gai4)
        ///4E11 (chou3)
        ///4E12 (chou3)
        ///4E13 (zhuan1)
        ///4E14 (qie3,ju1)
        ///4E15 (pi1)
        ///4E16 (shi4)
        ///4E17 (shi4)
        ///4E18 (qiu1)
        ///4E19 (bing3)
        ///4E1A (ye4)
        ///4E1B (cong2)
        ///4E1C (dong1)
        ///4E1D (si1)
        ///4E1E (cheng2)
        ///4E1F (diu1)
        ///4E20 (qiu1)
        ///4E21 (liang3) [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
    }
}
