//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hyjiacan.py4n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PinyinDbResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PinyinDbResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("hyjiacan.py4n.PinyinDbResource", typeof(PinyinDbResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 3007 (ling2)
        ///4E00 (yi1)
        ///4E01 (ding1,zheng1)
        ///4E02 (kao3)
        ///4E03 (qi1)
        ///4E04 (shang4,shang3)
        ///4E05 (xia4)
        ///4E06 (none0)
        ///4E07 (wan4,mo4)
        ///4E08 (zhang4)
        ///4E09 (san1)
        ///4E0A (shang4,shang3)
        ///4E0B (xia4)
        ///4E0C (ji1)
        ///4E0D (bu4,bu2,fou3)
        ///4E0E (yu3,yu4,yu2)
        ///4E0F (mian3)
        ///4E10 (gai4)
        ///4E11 (chou3)
        ///4E12 (chou3)
        ///4E13 (zhuan1)
        ///4E14 (qie3,ju1)
        ///4E15 (pi1)
        ///4E16 (shi4)
        ///4E17 (shi4)
        ///4E18 (qiu1)
        ///4E19 (bing3)
        ///4E1A (ye4)
        ///4E1B (cong2)
        ///4E1C (dong1)
        ///4E1D (si1)
        ///4E1E (cheng2)
        ///4E1F (diu1)
        ///4E20 (qiu1)
        ///4E21 (liang3) [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艾  (ai4)
        ///安  (an1)
        ///敖  (ao2)
        ///卞  (bian4)
        ///别  (bie2)
        ///边  (bian1)
        ///暴  (bao4)
        ///鲍  (bao4)
        ///白  (bai2)
        ///贝  (bei4)
        ///毕  (bi4)
        ///薄  (bo2)
        ///步  (bu4)
        ///巴  (ba1)
        ///班  (ban1)
        ///包  (bao1)
        ///贲  (ben1)
        ///柏  (bai3)
        ///卜  (bu3)
        ///柴  (chai2)
        ///单于  (chan2 yu2)
        ///常  (chang2)
        ///巢  (chao2)
        ///晁  (chao2)
        ///陈  (chen2)
        ///成  (cheng2)
        ///程  (cheng2)
        ///池  (chi2)
        ///淳于  (chun2 yu2)
        ///昌  (chang1)
        ///车  (che1)
        ///充  (chong1)
        ///储  (chu3)
        ///褚  (chu3)
        ///崔  (cui1)
        ///蔡  (cai4)
        ///曹  (cao2)
        ///岑  (cen2)
        ///从  (cong2)
        ///苍  (cang1)
        ///刁  (diao1)
        ///段  (duan4)
        ///戴  (dai4)
        ///邓  (deng4)
        ///第五  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
    }
}
